= Lenovo
:toc:
:toclevels: 1

== B50-70 20384 (b50-70-20384.bin)

[horizontal]
File path:: `lenovo/b50-70-20384.bin`
Product name:: 20384
Product version:: Lenovo B50-70
Product family:: IDEAPAD
Firmware vendor:: LENOVO
Firmware version:: 9DCN22WW(V2.03)
Release date:: 2014-08-21
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 4  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `7` | Cache information | 4  a| `0x000A`, `0x000B`, `0x000C`, `0x000D`
a| `8` | Port connector information | 16  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 8  a| `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`
a| `11` | OEM strings | 1  a| `0x0026`
a| `12` | System configuration options | 1  a| `0x0027`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `15` | System event log | 1  a| `0x0029`
a| `16` | Physical memory array | 1  a| `0x002A`
a| `17` | Memory device | 4  a| `0x002B`, `0x002C`, `0x002D`, `0x002E`
a| `18` | 32-bit memory error information | 3  a| `0x002F`, `0x0030`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0032`
a| `20` | Memory device mapped address | 2  a| `0x0033`, `0x0034`
a| `21` | Built-in pointing device | 1  a| `0x0035`
a| `22` | Portable battery | 1  a| `0x0036`
a| `24` | Hardware security | 1  a| `0x0037`
a| `26` | Voltage probe | 1  a| `0x0038`
a| `27` | Cooling device | 1  a| `0x0039`
a| `32` | System boot information | 1  a| `0x003A`
a| `39` | System power supply | 1  a| `0x003B`
a| `40` | Additional information | 1  a| `0x003C`
a| `41` | Onboard devices extended information | 1  a| `0x003D`
a| `127` | End of table | 1  a| `0x0043`
a| `128` | OEM-specific | 1  a| `0x003E`
a| `133` | OEM-specific | 1  a| `0x003F`
a| `136` | OEM-specific | 1  a| `0x0040`
a| `221` | OEM-specific | 2  a| `0x0041`, `0x0042`
|===
== B590 (b590.bin)

[horizontal]
File path:: `lenovo/b590.bin`
Product name:: INVALID
Product version:: Lenovo
Product family:: Lenovo
Firmware vendor:: LENOVO
Firmware version:: H5ET85WW(1.23)
Release date:: 2014-04-15
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0005`
a| `7` | Cache information | 4  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `8` | Port connector information | 8  a| `0x0010`, `0x0011`, `0x0014`, `0x0017`, `0x0019`, `0x001A`, `0x001B`, `0x001C`
a| `9` | System slots | 2  a| `0x0026`, `0x0027`
a| `10` | Onboard devices information | 1  a| `0x0029`
a| `12` | System configuration options | 1  a| `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `15` | System event log | 1  a| `0x0035`
a| `16` | Physical memory array | 1  a| `0x000C`
a| `17` | Memory device | 2  a| `0x000D`, `0x000E`
a| `18` | 32-bit memory error information | 1  a| `0x002E`
a| `19` | Memory array mapped address | 1  a| `0x000F`
a| `21` | Built-in pointing device | 2  a| `0x002F`, `0x0030`
a| `22` | Portable battery | 2  a| `0x002C`, `0x002D`
a| `24` | Hardware security | 1  a| `0x0036`
a| `126` | Inactive | 15  a| `0x0012`, `0x0013`, `0x0015`, `0x0016`, `0x0018`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0028`
a| `127` | End of table | 1  a| `0xFEFF`
a| `129` | OEM-specific | 1  a| `0x000A`
a| `131` | OEM-specific | 2  a| `0x000B`, `0x0031`
a| `132` | OEM-specific | 1  a| `0x0037`
a| `133` | OEM-specific | 1  a| `0x0033`
a| `134` | OEM-specific | 1  a| `0x0004`
a| `135` | OEM-specific | 3  a| `0x0032`, `0x0034`, `0x0038`
a| `140` | OEM-specific | 1  a| `0x0039`
|===
== IdeaPad G580 20150 (ideapad-g580-20150.bin)

[horizontal]
File path:: `lenovo/ideapad-g580-20150.bin`
Product name:: 20150
Product version:: Lenovo G580
Product family:: IDEAPAD
Firmware vendor:: LENOVO
Firmware version:: 5ECN96WW(V9.01)
Release date:: 2013-03-14
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 2  a| `0x0006`, `0x0007`
a| `7` | Cache information | 4  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `8` | Port connector information | 16  a| `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 8  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `11` | OEM strings | 1  a| `0x0024`
a| `12` | System configuration options | 1  a| `0x0025`
a| `13` | Firmware language information | 1  a| `0x0026`
a| `15` | System event log | 1  a| `0x0027`
a| `16` | Physical memory array | 1  a| `0x0028`
a| `17` | Memory device | 2  a| `0x0029`, `0x002A`
a| `18` | 32-bit memory error information | 3  a| `0x002B`, `0x002C`, `0x002D`
a| `19` | Memory array mapped address | 1  a| `0x002E`
a| `20` | Memory device mapped address | 2  a| `0x002F`, `0x0030`
a| `21` | Built-in pointing device | 1  a| `0x0031`
a| `22` | Portable battery | 1  a| `0x0032`
a| `26` | Voltage probe | 1  a| `0x0033`
a| `27` | Cooling device | 1  a| `0x0034`
a| `32` | System boot information | 1  a| `0x0035`
a| `39` | System power supply | 1  a| `0x0036`
a| `40` | Additional information | 1  a| `0x0037`
a| `41` | Onboard devices extended information | 1  a| `0x0038`
a| `127` | End of table | 1  a| `0x003C`
a| `128` | OEM-specific | 1  a| `0x0039`
a| `133` | OEM-specific | 1  a| `0x003A`
a| `136` | OEM-specific | 1  a| `0x003B`
|===
== IdeaPad Slim 5 14IRL8 (ideapad-slim-5-14irl8.bin)

[horizontal]
File path:: `lenovo/ideapad-slim-5-14irl8.bin`
Product name:: 82XD
Product version:: IdeaPad Slim 5 14IRL8
Product family:: IdeaPad Slim 5 14IRL8
Firmware vendor:: LENOVO
Firmware version:: LACN29WW
Release date:: 2023-09-01
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 8  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `8` | Port connector information | 17  a| `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 5  a| `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `11` | OEM strings | 1  a| `0x0023`
a| `12` | System configuration options | 1  a| `0x0024`
a| `13` | Firmware language information | 1  a| `0x0025`
a| `14` | Group associations | 2  a| `0x0026`, `0x004D`
a| `15` | System event log | 1  a| `0x0027`
a| `16` | Physical memory array | 1  a| `0x0028`
a| `17` | Memory device | 2  a| `0x0029`, `0x002A`
a| `19` | Memory array mapped address | 1  a| `0x002B`
a| `20` | Memory device mapped address | 8  a| `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`
a| `21` | Built-in pointing device | 1  a| `0x0034`
a| `22` | Portable battery | 1  a| `0x0035`
a| `24` | Hardware security | 1  a| `0x0036`
a| `26` | Voltage probe | 1  a| `0x0037`
a| `27` | Cooling device | 1  a| `0x0038`
a| `28` | Temperature probe | 1  a| `0x0039`
a| `32` | System boot information | 1  a| `0x003A`
a| `39` | System power supply | 1  a| `0x003B`
a| `40` | Additional information | 1  a| `0x003C`
a| `41` | Onboard devices extended information | 1  a| `0x003D`
a| `43` | TPM device | 1  a| `0x003E`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x003F`
a| `129` | OEM-specific | 1  a| `0x0040`
a| `131` | OEM-specific | 1  a| `0x0041`
a| `133` | OEM-specific | 1  a| `0x0042`
a| `136` | OEM-specific | 1  a| `0x0043`
a| `200` | OEM-specific | 1  a| `0x0044`
a| `219` | OEM-specific | 1  a| `0x0045`
a| `221` | OEM-specific | 6  a| `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`
a| `248` | OEM-specific | 1  a| `0x004C`
|===
== IdeaPad Z565 20066 (ideapad-z565-20066.bin)

[horizontal]
File path:: `lenovo/ideapad-z565-20066.bin`
Product name:: 20066
Product version:: IdeaPad Z565
Product family:: Type1Family
Firmware vendor:: LENOVO
Firmware version:: 36CN23WW(V2.09)
Release date:: 2010-12-01
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0020`
a| `5` | Memory controller information | 1  a| `0x002E`
a| `6` | Memory module information | 2  a| `0x0026`, `0x002A`
a| `7` | Cache information | 2  a| `0x0021`, `0x0022`
a| `8` | Port connector information | 16  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 5  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `16` | Physical memory array | 1  a| `0x0023`
a| `17` | Memory device | 2  a| `0x0024`, `0x0028`
a| `18` | 32-bit memory error information | 3  a| `0x0025`, `0x0029`, `0x002C`
a| `19` | Memory array mapped address | 1  a| `0x002D`
a| `20` | Memory device mapped address | 2  a| `0x0027`, `0x002B`
a| `21` | Built-in pointing device | 1  a| `0x000B`
a| `32` | System boot information | 1  a| `0x000C`
a| `40` | Additional information | 1  a| `0x001E`
a| `41` | Onboard devices extended information | 1  a| `0x001F`
a| `127` | End of table | 1  a| `0x0030`
a| `129` | OEM-specific | 1  a| `0x000D`
a| `133` | OEM-specific | 1  a| `0x002F`
|===
== ThinkBook 15 G2 ITL 20VE (thinkbook-15-g2-itl-20ve.bin)

[horizontal]
File path:: `lenovo/thinkbook-15-g2-itl-20ve.bin`
Product name:: 20VE
Product version:: ThinkBook 15 G2 ITL
Product family:: ThinkBook 15 G2 ITL
Firmware vendor:: LENOVO
Firmware version:: F8CN46WW(V2.09)
Release date:: 2021-12-24
SMBIOS version:: 3.3.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 4  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `8` | Port connector information | 17  a| `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `9` | System slots | 5  a| `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `11` | OEM strings | 1  a| `0x001F`
a| `12` | System configuration options | 1  a| `0x0020`
a| `13` | Firmware language information | 1  a| `0x0021`
a| `14` | Group associations | 2  a| `0x0022`, `0x0044`
a| `15` | System event log | 1  a| `0x0023`
a| `16` | Physical memory array | 1  a| `0x0024`
a| `17` | Memory device | 2  a| `0x0025`, `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0027`
a| `20` | Memory device mapped address | 2  a| `0x0028`, `0x0029`
a| `21` | Built-in pointing device | 1  a| `0x002A`
a| `22` | Portable battery | 1  a| `0x002B`
a| `24` | Hardware security | 1  a| `0x002C`
a| `26` | Voltage probe | 1  a| `0x002D`
a| `27` | Cooling device | 1  a| `0x002E`
a| `28` | Temperature probe | 1  a| `0x002F`
a| `32` | System boot information | 1  a| `0x0030`
a| `39` | System power supply | 1  a| `0x0031`
a| `40` | Additional information | 1  a| `0x0032`
a| `41` | Onboard devices extended information | 1  a| `0x0033`
a| `43` | TPM device | 1  a| `0x0034`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0035`
a| `129` | OEM-specific | 1  a| `0x0036`
a| `130` | OEM-specific | 1  a| `0x0037`
a| `131` | OEM-specific | 1  a| `0x0038`
a| `133` | OEM-specific | 1  a| `0x0039`
a| `136` | OEM-specific | 1  a| `0x003A`
a| `200` | OEM-specific | 1  a| `0x003B`
a| `219` | OEM-specific | 1  a| `0x003C`
a| `221` | OEM-specific | 6  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`
a| `248` | OEM-specific | 1  a| `0x0043`
|===
== ThinkCentre M700 10HY (thinkcentre-m700-10hy.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m700-10hy.bin`
Product name:: 10HYS0UG00
Product version:: ThinkCentre M700
Product family:: ThinkCentre M700
Firmware vendor:: LENOVO
Firmware version:: FWKT9EA
Release date:: 2019-04-22
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004B`
a| `7` | Cache information | 4  a| `0x0047`, `0x0048`, `0x0049`, `0x004A`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 4  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `10` | Onboard devices information | 1  a| `0x0020`
a| `11` | OEM strings | 1  a| `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `15` | System event log | 1  a| `0x0050`
a| `16` | Physical memory array | 1  a| `0x004C`
a| `17` | Memory device | 2  a| `0x004D`, `0x004E`
a| `19` | Memory array mapped address | 1  a| `0x004F`
a| `20` | Memory device mapped address | 2  a| `0x0052`, `0x0053`
a| `24` | Hardware security | 1  a| `0x002D`
a| `26` | Voltage probe | 2  a| `0x0030`, `0x003F`
a| `27` | Cooling device | 3  a| `0x0036`, `0x0039`, `0x0041`
a| `28` | Temperature probe | 2  a| `0x0033`, `0x0040`
a| `29` | Electrical current probe | 2  a| `0x003C`, `0x0042`
a| `32` | System boot information | 1  a| `0x002E`
a| `34` | Management device | 1  a| `0x002F`
a| `35` | Management device component | 5  a| `0x0032`, `0x0035`, `0x0038`, `0x003B`, `0x003E`
a| `36` | Management device threshold data | 5  a| `0x0031`, `0x0034`, `0x0037`, `0x003A`, `0x003D`
a| `39` | System power supply | 1  a| `0x0043`
a| `41` | Onboard devices extended information | 3  a| `0x0044`, `0x0045`, `0x0046`
a| `127` | End of table | 1  a| `0x0000`
a| `130` | OEM-specific | 1  a| `0x0054`
a| `131` | OEM-specific | 1  a| `0x0055`
a| `133` | OEM-specific | 1  a| `0x0051`
a| `140` | OEM-specific | 1  a| `0x005B`
a| `221` | OEM-specific | 5  a| `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`
|===
== ThinkCentre M70s 11DB (thinkcentre-m70s-11db.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m70s-11db.bin`
Product name:: 11DBSA6W00
Product version:: ThinkCentre M70s
Product family:: ThinkCentre M70s
Firmware vendor:: LENOVO
Firmware version:: M2TKT56A
Release date:: 2023-09-06
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0053`
a| `7` | Cache information | 3  a| `0x0050`, `0x0051`, `0x0052`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `16` | Physical memory array | 1  a| `0x003C`
a| `17` | Memory device | 4  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`
a| `19` | Memory array mapped address | 1  a| `0x0041`
a| `20` | Memory device mapped address | 2  a| `0x0048`, `0x0049`
a| `24` | Hardware security | 1  a| `0x0024`
a| `26` | Voltage probe | 2  a| `0x0027`, `0x0036`
a| `27` | Cooling device | 3  a| `0x002D`, `0x0030`, `0x0038`
a| `28` | Temperature probe | 2  a| `0x002A`, `0x0037`
a| `29` | Electrical current probe | 2  a| `0x0033`, `0x0039`
a| `32` | System boot information | 1  a| `0x0025`
a| `34` | Management device | 1  a| `0x0026`
a| `35` | Management device component | 5  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`
a| `36` | Management device threshold data | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `39` | System power supply | 1  a| `0x003A`
a| `41` | Onboard devices extended information | 8  a| `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`
a| `43` | TPM device | 1  a| `0x003B`
a| `127` | End of table | 1  a| `0x0000`
a| `130` | OEM-specific | 1  a| `0x0054`
a| `131` | OEM-specific | 1  a| `0x0055`
a| `133` | OEM-specific | 1  a| `0x0047`
a| `221` | OEM-specific | 6  a| `0x004A`, `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`
|===
== ThinkCentre M720q 10T8 (thinkcentre-m720q-10t8.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m720q-10t8.bin`
Product name:: 10T8SMC200
Product version:: ThinkCentre M720q
Product family:: ThinkCentre M720q
Firmware vendor:: LENOVO
Firmware version:: M1UKT78A
Release date:: 2025-12-04
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0048`
a| `7` | Cache information | 3  a| `0x0045`, `0x0046`, `0x0047`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0062`
a| `14` | Group associations | 2  a| `0x0061`, `0x0063`
a| `15` | System event log | 1  a| `0x003F`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 2  a| `0x003C`, `0x003D`
a| `19` | Memory array mapped address | 1  a| `0x003E`
a| `20` | Memory device mapped address | 2  a| `0x004E`, `0x004F`
a| `24` | Hardware security | 1  a| `0x0024`
a| `26` | Voltage probe | 2  a| `0x0027`, `0x0036`
a| `27` | Cooling device | 3  a| `0x002D`, `0x0030`, `0x0038`
a| `28` | Temperature probe | 2  a| `0x002A`, `0x0037`
a| `29` | Electrical current probe | 2  a| `0x0033`, `0x0039`
a| `32` | System boot information | 1  a| `0x0025`
a| `34` | Management device | 1  a| `0x0026`
a| `35` | Management device component | 5  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`
a| `36` | Management device threshold data | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `39` | System power supply | 1  a| `0x003A`
a| `41` | Onboard devices extended information | 12  a| `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`
a| `43` | TPM device | 1  a| `0x0049`
a| `127` | End of table | 1  a| `0x0065`
a| `130` | OEM-specific | 1  a| `0x0050`
a| `131` | OEM-specific | 2  a| `0x0051`, `0x005F`
a| `133` | OEM-specific | 1  a| `0x004A`
a| `136` | OEM-specific | 1  a| `0x0060`
a| `219` | OEM-specific | 1  a| `0x0064`
a| `221` | OEM-specific | 6  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x005E`
|===
== ThinkCentre M720s 10ST (thinkcentre-m720s-10st.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m720s-10st.bin`
Product name:: 10STS04K00
Product version:: ThinkCentre M720s
Product family:: ThinkCentre M720s
Firmware vendor:: LENOVO
Firmware version:: M1UKT59A
Release date:: 2020-07-07
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004A`
a| `7` | Cache information | 3  a| `0x0047`, `0x0048`, `0x0049`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0066`
a| `14` | Group associations | 2  a| `0x0065`, `0x0067`
a| `15` | System event log | 1  a| `0x0041`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 4  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `19` | Memory array mapped address | 1  a| `0x0040`
a| `20` | Memory device mapped address | 3  a| `0x0051`, `0x0052`, `0x0053`
a| `24` | Hardware security | 1  a| `0x0024`
a| `26` | Voltage probe | 2  a| `0x0027`, `0x0036`
a| `27` | Cooling device | 3  a| `0x002D`, `0x0030`, `0x0038`
a| `28` | Temperature probe | 2  a| `0x002A`, `0x0037`
a| `29` | Electrical current probe | 2  a| `0x0033`, `0x0039`
a| `32` | System boot information | 1  a| `0x0025`
a| `34` | Management device | 1  a| `0x0026`
a| `35` | Management device component | 5  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`
a| `36` | Management device threshold data | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `39` | System power supply | 1  a| `0x003A`
a| `41` | Onboard devices extended information | 12  a| `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`, `0x0061`
a| `43` | TPM device | 1  a| `0x004B`
a| `127` | End of table | 1  a| `0x0069`
a| `130` | OEM-specific | 1  a| `0x0054`
a| `131` | OEM-specific | 2  a| `0x0055`, `0x0063`
a| `133` | OEM-specific | 1  a| `0x004C`
a| `136` | OEM-specific | 1  a| `0x0064`
a| `219` | OEM-specific | 1  a| `0x0068`
a| `221` | OEM-specific | 6  a| `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0062`
|===
== ThinkPad T14 Gen 2a 20XK (thinkpad-t14-g2a-20xk.bin)

[horizontal]
File path:: `lenovo/thinkpad-t14-g2a-20xk.bin`
Product name:: 20XKA001CD
Product version:: ThinkPad T14 Gen 2a
Product family:: ThinkPad T14 Gen 2a
Firmware vendor:: LENOVO
Firmware version:: R1MET62W (1.32 )
Release date:: 2025-06-26
SMBIOS version:: 3.3.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000E`
a| `1` | System information | 1  a| `0x000F`
a| `2` | Baseboard or module information | 1  a| `0x0010`
a| `3` | System enclosure or chassis | 1  a| `0x0011`
a| `4` | Processor information | 1  a| `0x0006`
a| `7` | Cache information | 3  a| `0x0003`, `0x0004`, `0x0005`
a| `8` | Port connector information | 15  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `9` | System slots | 6  a| `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`
a| `10` | Onboard devices information | 4  a| `0x0027`, `0x0028`, `0x0029`, `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `15` | System event log | 1  a| `0x0038`
a| `16` | Physical memory array | 1  a| `0x0001`
a| `17` | Memory device | 2  a| `0x0008`, `0x000B`
a| `18` | 32-bit memory error information | 4  a| `0x0000`, `0x0007`, `0x000A`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0002`
a| `20` | Memory device mapped address | 2  a| `0x0009`, `0x000C`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x002C`
a| `24` | Hardware security | 1  a| `0x0036`
a| `126` | Inactive | 1  a| `0x002D`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | OEM-specific | 1  a| `0x0034`
a| `132` | OEM-specific | 1  a| `0x0037`
a| `133` | OEM-specific | 1  a| `0x002E`
a| `134` | OEM-specific | 1  a| `0x000D`
a| `135` | OEM-specific | 2  a| `0x0030`, `0x0043`
a| `136` | OEM-specific | 1  a| `0x0035`
a| `140` | OEM-specific | 5  a| `0x002F`, `0x003E`, `0x003F`, `0x0040`, `0x0041`
a| `141` | OEM-specific | 6  a| `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x0042`
|===
== ThinkPad T14 Gen 3 21AJ (thinkpad-t14-g3-21aj.bin)

[horizontal]
File path:: `lenovo/thinkpad-t14-g3-21aj.bin`
Product name:: 21AJS3EP26
Product version:: ThinkPad T14 Gen 3
Product family:: ThinkPad T14 Gen 3
Firmware vendor:: LENOVO
Firmware version:: N3MET26W (1.25 )
Release date:: 2025-09-28
SMBIOS version:: 3.4.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x001B`
a| `1` | System information | 1  a| `0x001C`
a| `2` | Baseboard or module information | 1  a| `0x001D`
a| `3` | System enclosure or chassis | 1  a| `0x001E`
a| `4` | Processor information | 1  a| `0x001A`
a| `7` | Cache information | 8  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `8` | Port connector information | 6  a| `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0029`, `0x002D`
a| `9` | System slots | 1  a| `0x002F`
a| `12` | System configuration options | 1  a| `0x0030`
a| `13` | Firmware language information | 1  a| `0x0031`
a| `14` | Group associations | 1  a| `0x003A`
a| `15` | System event log | 1  a| `0x0043`
a| `16` | Physical memory array | 1  a| `0x0001`
a| `17` | Memory device | 8  a| `0x0002`, `0x0003`, `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `18` | 32-bit memory error information | 1  a| `0x003E`
a| `19` | Memory array mapped address | 1  a| `0x000A`
a| `21` | Built-in pointing device | 2  a| `0x003F`, `0x0040`
a| `22` | Portable battery | 1  a| `0x0032`
a| `24` | Hardware security | 1  a| `0x003C`
a| `43` | TPM device | 1  a| `0x000B`
a| `126` | Inactive | 11  a| `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x002A`, `0x002B`, `0x002C`, `0x002E`, `0x0033`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | OEM-specific | 1  a| `0x0037`
a| `131` | OEM-specific | 2  a| `0x0038`, `0x0041`
a| `132` | OEM-specific | 1  a| `0x003D`
a| `133` | OEM-specific | 2  a| `0x0034`, `0x0035`
a| `134` | OEM-specific | 1  a| `0x0000`
a| `135` | OEM-specific | 2  a| `0x0036`, `0x004B`
a| `136` | OEM-specific | 1  a| `0x0042`
a| `140` | OEM-specific | 5  a| `0x0039`, `0x0044`, `0x0045`, `0x004C`, `0x004D`
a| `141` | OEM-specific | 6  a| `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004E`
a| `219` | OEM-specific | 1  a| `0x003B`
a| `221` | OEM-specific | 6  a| `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`
|===
== ThinkPad T61p 6460-6XG (thinkpad-t61p-6460-6xg.bin)

[horizontal]
File path:: `lenovo/thinkpad-t61p-6460-6xg.bin`
Product name:: 64606XG
Product version:: ThinkPad T61p
Product family:: ThinkPad T61p
Firmware vendor:: LENOVO
Firmware version:: 7LET56WW (1.26 )
Release date:: 2007-10-18
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0006`
a| `5` | Memory controller information | 1  a| `0x0007`
a| `6` | Memory module information | 2  a| `0x0008`, `0x0009`
a| `7` | Cache information | 3  a| `0x000A`, `0x000B`, `0x000C`
a| `8` | Port connector information | 9  a| `0x000D`, `0x000E`, `0x000F`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x001F`
a| `9` | System slots | 3  a| `0x0020`, `0x0021`, `0x0024`
a| `10` | Onboard devices information | 1  a| `0x0027`
a| `11` | OEM strings | 1  a| `0x0028`
a| `13` | Firmware language information | 1  a| `0x0029`
a| `15` | System event log | 1  a| `0x002A`
a| `16` | Physical memory array | 1  a| `0x002B`
a| `17` | Memory device | 2  a| `0x002C`, `0x002D`
a| `18` | 32-bit memory error information | 1  a| `0x002E`
a| `19` | Memory array mapped address | 1  a| `0x002F`
a| `20` | Memory device mapped address | 2  a| `0x0030`, `0x0031`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x0034`
a| `24` | Hardware security | 1  a| `0x0036`
a| `32` | System boot information | 1  a| `0x0037`
a| `126` | Inactive | 17  a| `0x0004`, `0x0005`, `0x0010`, `0x0011`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x0022`, `0x0023`, `0x0025`, `0x0026`, `0x0035`
a| `127` | End of table | 1  a| `0x0048`
a| `129` | OEM-specific | 1  a| `0x0046`
a| `130` | OEM-specific | 1  a| `0x0047`
a| `131` | OEM-specific | 2  a| `0x0038`, `0x0039`
a| `132` | OEM-specific | 1  a| `0x003A`
a| `133` | OEM-specific | 1  a| `0x003B`
a| `134` | OEM-specific | 2  a| `0x003C`, `0x003D`
a| `135` | OEM-specific | 4  a| `0x003E`, `0x003F`, `0x0040`, `0x0041`
a| `136` | OEM-specific | 1  a| `0x0042`
a| `137` | OEM-specific | 1  a| `0x0043`
a| `138` | OEM-specific | 1  a| `0x0044`
a| `139` | OEM-specific | 1  a| `0x0045`
|===
== ThinkPad X220 4290LE6 (thinkpad-x220-4290le6.bin)

[horizontal]
File path:: `lenovo/thinkpad-x220-4290le6.bin`
Product name:: 4290LE6
Product version:: ThinkPad X220
Product family:: ThinkPad X220
Firmware vendor:: LENOVO
Firmware version:: 8DET76WW (1.46 )
Release date:: 2018-06-21
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000D`
a| `1` | System information | 1  a| `0x000E`
a| `2` | Baseboard or module information | 1  a| `0x000F`
a| `3` | System enclosure or chassis | 1  a| `0x0010`
a| `4` | Processor information | 1  a| `0x0001`
a| `7` | Cache information | 3  a| `0x0002`, `0x0003`, `0x0004`
a| `8` | Port connector information | 8  a| `0x0011`, `0x0012`, `0x0015`, `0x0018`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 2  a| `0x0026`, `0x0027`
a| `10` | Onboard devices information | 1  a| `0x0029`
a| `12` | System configuration options | 1  a| `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `15` | System event log | 1  a| `0x0036`
a| `16` | Physical memory array | 1  a| `0x0005`
a| `17` | Memory device | 2  a| `0x0006`, `0x0007`
a| `18` | 32-bit memory error information | 1  a| `0x002E`
a| `19` | Memory array mapped address | 1  a| `0x0008`
a| `21` | Built-in pointing device | 2  a| `0x002F`, `0x0030`
a| `22` | Portable battery | 1  a| `0x002C`
a| `24` | Hardware security | 1  a| `0x003C`
a| `126` | Inactive | 15  a| `0x0013`, `0x0014`, `0x0016`, `0x0017`, `0x0019`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0028`, `0x002D`
a| `127` | End of table | 1  a| `0xFEFF`
a| `129` | OEM-specific | 1  a| `0x0009`
a| `130` | OEM-specific | 1  a| `0x000A`
a| `131` | OEM-specific | 2  a| `0x000B`, `0x0031`
a| `132` | OEM-specific | 1  a| `0x003D`
a| `133` | OEM-specific | 1  a| `0x0035`
a| `134` | OEM-specific | 2  a| `0x0000`, `0x000C`
a| `135` | OEM-specific | 3  a| `0x0033`, `0x0034`, `0x003E`
a| `136` | OEM-specific | 1  a| `0x0032`
a| `140` | OEM-specific | 5  a| `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`
|===
== ThinkPad X280 20KF (thinkpad-x280-20kf.bin)

[horizontal]
File path:: `lenovo/thinkpad-x280-20kf.bin`
Product name:: 20KFCTO1WW
Product version:: ThinkPad X280
Product family:: ThinkPad X280
Firmware vendor:: LENOVO
Firmware version:: N20ET56W (1.41 )
Release date:: 2020-10-08
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000B`
a| `1` | System information | 1  a| `0x000C`
a| `2` | Baseboard or module information | 1  a| `0x000D`
a| `3` | System enclosure or chassis | 1  a| `0x000E`
a| `4` | Processor information | 1  a| `0x000A`
a| `7` | Cache information | 3  a| `0x0007`, `0x0008`, `0x0009`
a| `8` | Port connector information | 7  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0018`, `0x001A`, `0x001E`
a| `9` | System slots | 2  a| `0x0020`, `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0023`
a| `14` | Group associations | 2  a| `0x0001`, `0x0039`
a| `15` | System event log | 1  a| `0x002E`
a| `16` | Physical memory array | 1  a| `0x0003`
a| `17` | Memory device | 2  a| `0x0004`, `0x0005`
a| `18` | 32-bit memory error information | 1  a| `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0006`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x0024`
a| `24` | Hardware security | 1  a| `0x002F`
a| `126` | Inactive | 11  a| `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0019`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0025`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | OEM-specific | 1  a| `0x0028`
a| `131` | OEM-specific | 2  a| `0x0029`, `0x0034`
a| `132` | OEM-specific | 1  a| `0x0030`
a| `133` | OEM-specific | 1  a| `0x0026`
a| `134` | OEM-specific | 1  a| `0x0002`
a| `135` | OEM-specific | 2  a| `0x0027`, `0x003B`
a| `136` | OEM-specific | 1  a| `0x0035`
a| `140` | OEM-specific | 5  a| `0x0036`, `0x0037`, `0x0038`, `0x003C`, `0x003D`
a| `219` | OEM-specific | 1  a| `0x003A`
a| `221` | OEM-specific | 4  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `222` | OEM-specific | 1  a| `0x0000`
|===
