= Lenovo
:toc:
:toclevels: 1

== X79R-AX (x79r-ax.bin)

[horizontal]
File path:: `ecs/x79r-ax.bin`
Product name:: X79R-AX
Product version:: 1.0
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 4.6.5
Release date:: 2013-12-04
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 24  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 6  a| `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`
a| `10` | Onboard devices information | 1  a| `0x0026`
a| `11` | OEM strings | 1  a| `0x0027`
a| `12` | System configuration options | 1  a| `0x0028`
a| `16` | Physical memory array | 1  a| `0x0029`
a| `17` | Memory device | 4  a| `0x002B`, `0x002D`, `0x002F`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x002A`
a| `20` | Memory device mapped address | 4  a| `0x002C`, `0x002E`, `0x0030`, `0x0032`
a| `26` | Voltage probe | 4  a| `0x0035`, `0x0045`, `0x0048`, `0x005D`
a| `27` | Cooling device | 5  a| `0x003B`, `0x003E`, `0x004E`, `0x0054`, `0x005F`
a| `28` | Temperature probe | 4  a| `0x0038`, `0x004B`, `0x0051`, `0x005E`
a| `29` | Electrical current probe | 4  a| `0x0041`, `0x0057`, `0x005A`, `0x0060`
a| `32` | System boot information | 1  a| `0x0033`
a| `34` | Management device | 2  a| `0x0034`, `0x0044`
a| `35` | Management device component | 13  a| `0x0037`, `0x003A`, `0x003D`, `0x0040`, `0x0043`, `0x0047`, `0x004A`, `0x004D`, `0x0050`, `0x0053`, `0x0056`, `0x0059`, `0x005C`
a| `36` | Management device threshold data | 13  a| `0x0036`, `0x0039`, `0x003C`, `0x003F`, `0x0042`, `0x0046`, `0x0049`, `0x004C`, `0x004F`, `0x0052`, `0x0055`, `0x0058`, `0x005B`
a| `39` | System power supply | 1  a| `0x0061`
a| `41` | Onboard devices extended information | 1  a| `0x0062`
a| `127` | End of table | 1  a| `0x0067`
|===
