= IBM
:toc:
:toclevels: 1

== System x3950 M2 [1] (x3950-m2-1.bin)

[horizontal]
File path:: `ibm/x3950-m2-1.bin`
Product name:: IBM 3850 M2 / x3950 M2 -[71413RM]-
Product version:: None
Product family:: None
Firmware vendor:: IBM
Firmware version:: -[A3E148AUS-1.07]-
Release date:: 2008-11-05
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 6  a| `0x0002`, `0x0003`, `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `3` | System enclosure or chassis | 1  a| `0x003A`
a| `4` | Processor information | 4  a| `0x00A2`, `0x00A3`, `0x00A4`, `0x00A5`
a| `7` | Cache information | 4  a| `0x0043`, `0x0046`, `0x0049`, `0x004C`
a| `8` | Port connector information | 17  a| `0x00C2`, `0x00C3`, `0x00C4`, `0x00C5`, `0x00C6`, `0x00C7`, `0x00C8`, `0x00C9`, `0x00CA`, `0x00CB`, `0x00CC`, `0x00CD`, `0x00CE`, `0x00CF`, `0x00D0`, `0x00D1`, `0x00D2`
a| `9` | System slots | 7  a| `0x012B`, `0x012C`, `0x012D`, `0x012E`, `0x012F`, `0x0130`, `0x0131`
a| `11` | OEM strings | 1  a| `0x016B`
a| `12` | System configuration options | 4  a| `0x016C`, `0x016D`, `0x016E`, `0x016F`
a| `13` | Firmware language information | 1  a| `0x0170`
a| `16` | Physical memory array | 1  a| `0x0171`
a| `17` | Memory device | 32  a| `0x0172`, `0x0173`, `0x0174`, `0x0175`, `0x0176`, `0x0177`, `0x0178`, `0x0179`, `0x017A`, `0x017B`, `0x017C`, `0x017D`, `0x017E`, `0x017F`, `0x0180`, `0x0181`, `0x0182`, `0x0183`, `0x0184`, `0x0185`, `0x0186`, `0x0187`, `0x0188`, `0x0189`, `0x018A`, `0x018B`, `0x018C`, `0x018D`, `0x018E`, `0x018F`, `0x0190`, `0x0191`
a| `19` | Memory array mapped address | 1  a| `0x0272`
a| `32` | System boot information | 1  a| `0x0273`
a| `38` | IPMI device information | 1  a| `0x0274`
a| `127` | End of table | 1  a| `0x027C`
|===
== System x3950 M2 [2] (x3950-m2-2.bin)

[horizontal]
File path:: `ibm/x3950-m2-2.bin`
Product name:: IBM 3850 M2 / x3950 M2 -[71413RM]-
Product version:: None
Product family:: None
Firmware vendor:: IBM
Firmware version:: -[A3E129AUS-1.03]-
Release date:: 2008-03-05
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 6  a| `0x0002`, `0x0003`, `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `3` | System enclosure or chassis | 1  a| `0x003A`
a| `4` | Processor information | 4  a| `0x00A2`, `0x00A3`, `0x00A4`, `0x00A5`
a| `7` | Cache information | 4  a| `0x0043`, `0x0046`, `0x0049`, `0x004C`
a| `8` | Port connector information | 17  a| `0x00C2`, `0x00C3`, `0x00C4`, `0x00C5`, `0x00C6`, `0x00C7`, `0x00C8`, `0x00C9`, `0x00CA`, `0x00CB`, `0x00CC`, `0x00CD`, `0x00CE`, `0x00CF`, `0x00D0`, `0x00D1`, `0x00D2`
a| `9` | System slots | 7  a| `0x012B`, `0x012C`, `0x012D`, `0x012E`, `0x012F`, `0x0130`, `0x0131`
a| `11` | OEM strings | 1  a| `0x016B`
a| `12` | System configuration options | 4  a| `0x016C`, `0x016D`, `0x016E`, `0x016F`
a| `13` | Firmware language information | 1  a| `0x0170`
a| `16` | Physical memory array | 1  a| `0x0171`
a| `17` | Memory device | 32  a| `0x0172`, `0x0173`, `0x0174`, `0x0175`, `0x0176`, `0x0177`, `0x0178`, `0x0179`, `0x017A`, `0x017B`, `0x017C`, `0x017D`, `0x017E`, `0x017F`, `0x0180`, `0x0181`, `0x0182`, `0x0183`, `0x0184`, `0x0185`, `0x0186`, `0x0187`, `0x0188`, `0x0189`, `0x018A`, `0x018B`, `0x018C`, `0x018D`, `0x018E`, `0x018F`, `0x0190`, `0x0191`
a| `19` | Memory array mapped address | 1  a| `0x0272`
a| `32` | System boot information | 1  a| `0x0273`
a| `38` | IPMI device information | 1  a| `0x0274`
a| `127` | End of table | 1  a| `0x027C`
|===
