= Miscellaneous
:toc:
:toclevels: 1

== Noname [1] (noname-1.bin)

[horizontal]
File path:: `misc/noname-1.bin`
Product name:: Default string
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: 5.16
Release date:: 2024-09-05
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 14  a| `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `9` | System slots | 4  a| `0x0024`, `0x0025`, `0x0026`, `0x0027`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x002A`
a| `16` | Physical memory array | 1  a| `0x000A`
a| `17` | Memory device | 2  a| `0x0011`, `0x0014`
a| `18` | 32-bit memory error information | 3  a| `0x0009`, `0x0010`, `0x0013`
a| `19` | Memory array mapped address | 1  a| `0x000B`
a| `20` | Memory device mapped address | 2  a| `0x0012`, `0x0015`
a| `32` | System boot information | 1  a| `0x0007`
a| `41` | Onboard devices extended information | 2  a| `0x0028`, `0x0029`
a| `43` | TPM device | 1  a| `0x0008`
a| `127` | End of table | 1  a| `0x002B`
|===
