= Intel
:toc:
:toclevels: 1

== NUC NUC5PPYB (nuc-nuc5ppyb.bin)

[horizontal]
File path:: `intel/nuc-nuc5ppyb.bin`
Product name:: None
Product version:: None
Product family:: None
Firmware vendor:: Intel Corp.
Firmware version:: PYBSWCEL.86A.0050.2016.0223.1234
Release date:: 2016-02-23
SMBIOS version:: 2.8

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0031`
a| `7` | Cache information | 2  a| `0x002F`, `0x0030`
a| `8` | Port connector information | 24  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 1  a| `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0032`
a| `16` | Physical memory array | 1  a| `0x0024`
a| `17` | Memory device | 1  a| `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0025`
a| `20` | Memory device mapped address | 1  a| `0x0027`
a| `32` | System boot information | 1  a| `0x0028`
a| `41` | Onboard devices extended information | 6  a| `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`
a| `126` | Inactive | 1  a| `0x0007`
a| `127` | End of table | 1  a| `0x0033`
|===
