//
// OpenDMI: DMI/SMBIOS library
// Copyright (c) 2025, Dmitry Sednev <dmitry@sednev.ru>
//
// SPDX-License-Identifier: BSD-3-Clause
//
#include <opendmi/processor.h>
#include <opendmi/utils.h>

static const char *dmi_processor_type_names[__DMI_PROCESSOR_TYPE_COUNT] =
{
    [DMI_PROCESSOR_TYPE_OTHER]   = "Other",
    [DMI_PROCESSOR_TYPE_UNKNOWN] = "Unknown",
    [DMI_PROCESSOR_TYPE_CENTRAL] = "Central processor",
    [DMI_PROCESSOR_TYPE_MATH]    = "Math processor",
    [DMI_PROCESSOR_TYPE_DSP]     = "DSP processor",
    [DMI_PROCESSOR_TYPE_VIDEO]   = "Video processor"
};

static const char *dmi_processor_upgrade_names[__DMI_PROCESSOR_UPGRADE_COUNT] =
{
    [DMI_PROCESSOR_UPGRADE_OTHER]            = "Other",
    [DMI_PROCESSOR_UPGRADE_UNKNOWN]          = "Unknown",
    [DMI_PROCESSOR_UPGRADE_DAUGHTER_BOARD]   = "Daughter board",
    [DMI_PROCESSOR_UPGRADE_SOCKET_ZIF]       = "ZIF socket",
    [DMI_PROCESSOR_UPGRADE_PIGGY_BACK]       = "Replaceable piggy-back",
    [DMI_PROCESSOR_UPGRADE_NONE]             = "None",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LIF]       = "LIF socket",
    [DMI_PROCESSOR_UPGRADE_SLOT_1]           = "Slot 1",
    [DMI_PROCESSOR_UPGRADE_SLOT_2]           = "Slot 2",
    [DMI_PROCESSOR_UPGRADE_SOCKET_370PIN]    = "370-pin socket",
    [DMI_PROCESSOR_UPGRADE_SLOT_A]           = "Slot A",
    [DMI_PROCESSOR_UPGRADE_SLOT_M]           = "Slot M",
    [DMI_PROCESSOR_UPGRADE_SOCKET_423]       = "Socket 423",
    [DMI_PROCESSOR_UPGRADE_SOCKET_A]         = "Socket A (462)",
    [DMI_PROCESSOR_UPGRADE_SOCKET_478]       = "Socket 478",
    [DMI_PROCESSOR_UPGRADE_SOCKET_754]       = "Socket 754",
    [DMI_PROCESSOR_UPGRADE_SOCKET_940]       = "Socket 940",
    [DMI_PROCESSOR_UPGRADE_SOCKET_939]       = "Socket 939",
    [DMI_PROCESSOR_UPGRADE_SOCKET_MPGA604]   = "Socket mPGA604",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA771]    = "Socket LGA771",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA775]    = "Socket LGA775",
    [DMI_PROCESSOR_UPGRADE_SOCKET_S1]        = "Socket S1",
    [DMI_PROCESSOR_UPGRADE_SOCKET_AM2]       = "Socket AM2",
    [DMI_PROCESSOR_UPGRADE_SOCKET_F]         = "Socket F (1207)",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1366]   = "Socket LGA1366",
    [DMI_PROCESSOR_UPGRADE_SOCKET_G34]       = "Socket G34",
    [DMI_PROCESSOR_UPGRADE_SOCKET_AM3]       = "Socket AM3",
    [DMI_PROCESSOR_UPGRADE_SOCKET_C32]       = "Socket C32",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1156]   = "Socket LGA1156",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1567]   = "Socket LGA1567",
    [DMI_PROCESSOR_UPGRADE_SOCKET_PGA988A]   = "Socket PGA988A",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1288]   = "Socket BGA1288",
    [DMI_PROCESSOR_UPGRADE_SOCKET_RPGA988B]  = "Socket rPGA988B",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1023]   = "Socket BGA1023",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1224]   = "Socket BGA1224",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1155]   = "Socket LGA1155",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1356]   = "Socket LGA1356",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA2011]   = "Socket LGA2011",
    [DMI_PROCESSOR_UPGRADE_SOCKET_FS1]       = "Socket FS1",
    [DMI_PROCESSOR_UPGRADE_SOCKET_FS2]       = "Socket FS2",
    [DMI_PROCESSOR_UPGRADE_SOCKET_FM1]       = "Socket FM1",
    [DMI_PROCESSOR_UPGRADE_SOCKET_FM2]       = "Socket FM2",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA2011_3] = "Socket LGA2011-3",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1356_3] = "Socket LGA1356-3",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1150]   = "Socket LGA1150",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1168]   = "Socket BGA1168",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1234]   = "Socket BGA1234",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1364]   = "Socket BGA1364",
    [DMI_PROCESSOR_UPGRADE_SOCKET_AM4]       = "Socket AM4",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1151]   = "Socket LGA1151",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1356]   = "Socket BGA1356",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1440]   = "Socket BGA1440",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1515]   = "Socket BGA1515",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA3647_1] = "Socket LGA3647-1",
    [DMI_PROCESSOR_UPGRADE_SOCKET_SP3]       = "Socket SP3",
    [DMI_PROCESSOR_UPGRADE_SOCKET_SP3R2]     = "Socket SP3r2",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA2066]   = "Socket LGA2066",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1392]   = "Socket BGA1392",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1510]   = "Socket BGA1510",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1528]   = "Socket BGA1528",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA4189]   = "Socket LGA4189",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1200]   = "Socket LGA1200",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA4677]   = "Socket LGA4677",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1700]   = "Socket LGA1700",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1744]   = "Socket BGA1744",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1781]   = "Socket BGA1781",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1211]   = "Socket BGA1211",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA2422]   = "Socket BGA2422",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1211]   = "Socket LGA1211",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA2422]   = "Socket LGA2422",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA5773]   = "Socket LGA5773",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA5773]   = "Socket BGA5773",
    [DMI_PROCESSOR_UPGRADE_SOCKET_AM5]       = "Socket AM5",
    [DMI_PROCESSOR_UPGRADE_SOCKET_SP5]       = "Socket SP5",
    [DMI_PROCESSOR_UPGRADE_SOCKET_SP6]       = "Socket SP6",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA883]    = "Socket BGA883",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1190]   = "Socket BGA1190",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA4129]   = "Socket BGA4129",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA4710]   = "Socket LGA4710",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA7529]   = "Socket LGA7529",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1964]   = "Socket BGA1964",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA1792]   = "Socket BGA1792",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA2049]   = "Socket BGA2049",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA2551]   = "Socket BGA2551",
    [DMI_PROCESSOR_UPGRADE_SOCKET_LGA1851]   = "Socket LGA1851",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA2114]   = "Socket BGA2114",
    [DMI_PROCESSOR_UPGRADE_SOCKET_BGA2833]   = "Socket BGA2833"
};

const char *dmi_processor_type_name(enum dmi_processor_type value)
{
    return dmi_name(dmi_processor_type_names, value, __DMI_PROCESSOR_TYPE_COUNT);
}

const char *dmi_processor_upgrade_name(enum dmi_processor_upgrade value)
{
    return dmi_name(dmi_processor_upgrade_names, value, __DMI_PROCESSOR_UPGRADE_COUNT);
}
