= Synology
:toc:
:toclevels: 1

== DiskStation DS718+ (ds718-plus.bin)

[horizontal]
File path:: `synology/ds718-plus.bin`
Product name:: DS718+
Product version:: 1.0
Product family:: DiskStation
Firmware vendor:: INSYDE Corp.
Firmware version:: M.231
Release date:: 2019-11-08
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 19  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`
a| `9` | System slots | 4  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `11` | OEM strings | 1  a| `0x001F`
a| `12` | System configuration options | 1  a| `0x0020`
a| `13` | Firmware language information | 1  a| `0x0021`
a| `15` | System event log | 1  a| `0x0022`
a| `16` | Physical memory array | 1  a| `0x0023`
a| `17` | Memory device | 2  a| `0x0024`, `0x0025`
a| `19` | Memory array mapped address | 1  a| `0x0026`
a| `20` | Memory device mapped address | 2  a| `0x0027`, `0x0028`
a| `21` | Built-in pointing device | 1  a| `0x0029`
a| `22` | Portable battery | 1  a| `0x002A`
a| `26` | Voltage probe | 1  a| `0x002B`
a| `27` | Cooling device | 1  a| `0x002C`
a| `28` | Temperature probe | 1  a| `0x002D`
a| `32` | System boot information | 1  a| `0x002E`
a| `39` | System power supply | 1  a| `0x002F`
a| `41` | Onboard devices extended information | 1  a| `0x0030`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | OEM-specific | 1  a| `0x0031`
|===
